server:
  port: 8095

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Project1b/config
          username: erick.pinglo@hotmail.com
          password: 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
          default-label: master
  application:
    name: config-server-service
